export const EXECUTOR_TOOL_NAMES = [
  'directory_list',
  'file_read',
  'file_write',
  'file_delete',
  'git_reset',
  'git_push',
  'shell_exec',
  'test_run',
  'mcp_request',
  'mcp_resource_list',
  'mcp_resource_read',
  'mcp_prompt_list',
  'mcp_prompt_get',
  'mcp_tool_search',
  'web_search',
  'web_fetch',
  'plugin_tool',
  'audit_ui',
  'memory_store',
  'memory_query',
  'enter_plan_mode',
  'exit_plan_mode',
  'semantic_search',
  'grep',
  'glob',
  'workspace_symbol_search',
  'workspace_map',
  'git_context',
  'acquire_lock',
  'release_lock',
  'tool_catalog',
  'get_code_outline',
  'find_code_definition',
  'find_code_references',
  'load_skill_manifest',
  'kg_trace_path',
  'kg_search_graph',
  'kg_impact_analysis',
  'kg_architecture',
  'kg_index_status',
  'lsp',
] as const;

export type ExecutorToolName = (typeof EXECUTOR_TOOL_NAMES)[number];

export const MUTATING_EXECUTOR_TOOL_NAMES = [
  'file_write',
  'file_delete',
  'git_reset',
  'git_push',
  'shell_exec',
  'test_run',
  'memory_store',
  'enter_plan_mode',
  'exit_plan_mode',
  'acquire_lock',
  'release_lock',
] as const satisfies readonly ExecutorToolName[];
