// AUTO-GENERATED by tools/generate-tool-registry.ps1 - DO NOT EDIT MANUALLY
// Source: babel-cli/src/tools/tool-manifest.json (v1.0.0)
// Generated: 2026-07-02 02:25:48 -05:00

export const MANIFEST_TOOL_NAMES = [
  'acquire_lock',   'audit_ui',   'directory_list',   'enter_plan_mode',   'exit_plan_mode',   'file_delete',   'file_read',   'file_write',   'find_code_definition',   'find_code_references',   'get_code_outline',   'git_context',   'git_push',   'git_reset',   'glob',   'grep',   'kg_architecture',   'kg_impact_analysis',   'kg_index_status',   'kg_search_graph',   'kg_trace_path',   'load_skill_manifest',   'mcp_prompt_get',   'mcp_prompt_list',   'mcp_request',   'mcp_resource_list',   'mcp_resource_read',   'mcp_tool_search',   'memory_query',   'memory_store',   'plugin_tool',   'release_lock',   'semantic_search',   'shell_exec',   'test_run',   'tool_catalog',   'web_fetch',   'web_search',   'workspace_map',   'workspace_symbol_search',
] as const;

export type ManifestToolName = typeof MANIFEST_TOOL_NAMES[number];

export const MANIFEST_MUTATING_TOOL_NAMES: ManifestToolName[] = [
  'file_write',   'file_delete',   'shell_exec',   'test_run',   'memory_store',   'enter_plan_mode',   'exit_plan_mode',   'git_reset',   'git_push',   'acquire_lock',   'release_lock',
];

export const MANIFEST_READ_ONLY_TOOL_NAMES: ManifestToolName[] = [
  'directory_list',   'file_read',   'mcp_request',   'mcp_resource_list',   'mcp_resource_read',   'mcp_prompt_list',   'mcp_prompt_get',   'mcp_tool_search',   'web_search',   'web_fetch',   'plugin_tool',   'audit_ui',   'memory_query',   'semantic_search',   'grep',   'glob',   'workspace_symbol_search',   'get_code_outline',   'find_code_definition',   'find_code_references',   'load_skill_manifest',   'workspace_map',   'git_context',   'tool_catalog',   'kg_trace_path',   'kg_search_graph',   'kg_impact_analysis',   'kg_architecture',   'kg_index_status',
];

/** Tools requiring JIT human approval for certain operations */
export const MANIFEST_JIT_TOOL_NAMES: ManifestToolName[] = [
  'file_write',   'shell_exec',   'test_run',
];

/** Map of tool name to category */
export const MANIFEST_TOOL_CATEGORY_MAP: Record<ManifestToolName, string> = {
  'directory_list': 'filesystem',   'file_read': 'filesystem',   'file_write': 'filesystem',   'file_delete': 'filesystem',   'shell_exec': 'process',   'test_run': 'process',   'mcp_request': 'mcp',   'mcp_resource_list': 'mcp',   'mcp_resource_read': 'mcp',   'mcp_prompt_list': 'mcp',   'mcp_prompt_get': 'mcp',   'mcp_tool_search': 'mcp',   'web_search': 'web',   'web_fetch': 'web',   'plugin_tool': 'plugin',   'audit_ui': 'ui',   'memory_store': 'memory',   'memory_query': 'memory',   'enter_plan_mode': 'mode',   'exit_plan_mode': 'mode',   'semantic_search': 'search',   'grep': 'search',   'glob': 'search',   'workspace_symbol_search': 'search',   'get_code_outline': 'search',   'find_code_definition': 'search',   'find_code_references': 'search',   'load_skill_manifest': 'search',   'workspace_map': 'search',   'git_context': 'search',   'git_reset': 'vcs',   'git_push': 'vcs',   'acquire_lock': 'coordination',   'release_lock': 'coordination',   'tool_catalog': 'search',   'kg_trace_path': 'knowledge-graph',   'kg_search_graph': 'knowledge-graph',   'kg_impact_analysis': 'knowledge-graph',   'kg_architecture': 'knowledge-graph',   'kg_index_status': 'knowledge-graph',
};

/** Map of tool name to dry-run behavior */
export const MANIFEST_DRY_RUN_MAP: Record<ManifestToolName, string> = {
  'directory_list': 'live',   'file_read': 'live',   'file_write': 'shadow_write',   'file_delete': 'mocked',   'shell_exec': 'mocked',   'test_run': 'mocked',   'mcp_request': 'live',   'mcp_resource_list': 'live',   'mcp_resource_read': 'live',   'mcp_prompt_list': 'live',   'mcp_prompt_get': 'live',   'mcp_tool_search': 'live',   'web_search': 'live',   'web_fetch': 'live',   'plugin_tool': 'live',   'audit_ui': 'live',   'memory_store': 'mocked',   'memory_query': 'live',   'enter_plan_mode': 'stateful',   'exit_plan_mode': 'stateful',   'semantic_search': 'live',   'grep': 'live',   'glob': 'live',   'workspace_symbol_search': 'live',   'get_code_outline': 'live',   'find_code_definition': 'live',   'find_code_references': 'live',   'load_skill_manifest': 'live',   'workspace_map': 'live',   'git_context': 'live',   'git_reset': 'mocked',   'git_push': 'mocked',   'acquire_lock': 'stateful',   'release_lock': 'stateful',   'tool_catalog': 'live',   'kg_trace_path': 'live',   'kg_search_graph': 'live',   'kg_impact_analysis': 'live',   'kg_architecture': 'live',   'kg_index_status': 'live',
};
