/**
 * W3.1 / C-SH-03 — Evidence-backed draft PR body for /ship.
 *
 * Builds a PR description from implementor run evidence (writes, verification,
 * phase-gate counters, why-stopped, plan linkage) so the PR *proves* the work.
 */

import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

export interface ImplementorShipEvidence {
  task?: string;
  changed_files?: string[];
  write_count?: number;
  tools_before_first_write?: number;
  env_blocked?: boolean;
  phase_gate_write_block_count?: number;
  phase_gate_block_count?: number;
  verification?: Array<{ command: string; status: string; exit_code?: number | null }>;
  why_stopped?: string;
  plan_id?: string;
  linked_event_id?: string;
  review_verdict?: string;
  run_dir?: string;
  notes?: string[];
  status?: string;
}

export interface EvidencePrBodyOptions {
  /** Override title heading inside body. */
  heading?: string;
  /** Extra footer lines. */
  footer?: string[];
}

/**
 * Build markdown PR body from implementor evidence (pure).
 */
export function buildEvidencePrBody(
  evidence: ImplementorShipEvidence,
  options: EvidencePrBodyOptions = {},
): string {
  const heading = options.heading ?? '## Babel implementor evidence';
  const files = evidence.changed_files ?? [];
  const verification = evidence.verification ?? [];
  const notes = evidence.notes ?? [];

  const lines: string[] = [
    heading,
    '',
    '### Summary',
    evidence.task?.trim()
      ? `- **Task**: ${evidence.task.trim().slice(0, 500)}`
      : '- **Task**: (not recorded)',
    `- **Status**: ${evidence.status ?? 'unknown'}`,
    `- **Writes**: ${evidence.write_count ?? 0}`,
    evidence.tools_before_first_write != null
      ? `- **Tools before first write (TTF)**: ${evidence.tools_before_first_write}`
      : null,
    evidence.env_blocked != null ? `- **Env blocked**: ${evidence.env_blocked ? 'yes' : 'no'}` : null,
    evidence.phase_gate_write_block_count != null
      ? `- **Phase-gate write blocks**: ${evidence.phase_gate_write_block_count}`
      : null,
    evidence.review_verdict ? `- **Review-on-diff**: ${evidence.review_verdict}` : null,
    evidence.plan_id ? `- **Plan id**: \`${evidence.plan_id}\`` : null,
    evidence.linked_event_id ? `- **Linked event**: \`${evidence.linked_event_id}\`` : null,
    evidence.run_dir ? `- **Run dir**: \`${evidence.run_dir}\`` : null,
    '',
    '### Changed files',
    files.length > 0 ? files.map((f) => `- \`${f}\``).join('\n') : '- (none listed)',
    '',
    '### Verification',
  ].filter((x): x is string => x != null);

  if (verification.length === 0) {
    lines.push('- (no verification commands recorded — operator should confirm tests)');
  } else {
    for (const v of verification) {
      const code = v.exit_code != null ? ` exit=${v.exit_code}` : '';
      lines.push(`- **${v.status}** \`${v.command}\`${code}`);
    }
  }

  if (evidence.why_stopped?.trim()) {
    lines.push('', '### Why stopped', '```', evidence.why_stopped.trim().slice(0, 1500), '```');
  }

  if (notes.length > 0) {
    lines.push('', '### Notes', ...notes.map((n) => `- ${n}`));
  }

  lines.push(
    '',
    '### Test plan',
    '- [ ] Targeted unit tests for touched paths',
    '- [ ] Secret scan clean (ship hard-stop)',
    '- [ ] Review draft PR evidence section matches local run',
    '',
    '---',
    '_Generated by Babel implementor `/ship` (W3 evidence PR body)._',
  );

  if (options.footer?.length) {
    lines.push('', ...options.footer);
  }

  return lines.join('\n');
}

function tryReadJson(path: string): Record<string, unknown> | null {
  try {
    if (!existsSync(path)) return null;
    return JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Best-effort load of implementor fields from a Babel run directory / harness.
 */
export function loadImplementorShipEvidenceFromRunDir(runDir: string): ImplementorShipEvidence {
  const evidence: ImplementorShipEvidence = { run_dir: runDir };
  if (!runDir || !existsSync(runDir)) return evidence;

  const harnessCandidates = [
    join(runDir, 'harness.json'),
    ...safeList(runDir)
      .filter((f) => f.endsWith('-harness.json') || f === 'cli_payload.json')
      .map((f) => join(runDir, f)),
  ];

  for (const hp of harnessCandidates) {
    const raw = tryReadJson(hp);
    if (!raw) continue;

    const cli = (raw['cli_payload'] as Record<string, unknown> | undefined) ?? raw;
    if (typeof raw['status'] === 'string') evidence.status = raw['status'];
    if (typeof cli['status'] === 'string') evidence.status = String(cli['status']);
    if (typeof raw['write_count'] === 'number') evidence.write_count = raw['write_count'];
    if (typeof raw['tools_before_first_write'] === 'number') {
      evidence.tools_before_first_write = raw['tools_before_first_write'];
    }
    if (typeof raw['env_blocked'] === 'boolean') evidence.env_blocked = raw['env_blocked'];
    if (typeof raw['phase_gate_write_block_count'] === 'number') {
      evidence.phase_gate_write_block_count = raw['phase_gate_write_block_count'];
    }
    if (typeof raw['phase_gate_block_count'] === 'number') {
      evidence.phase_gate_block_count = raw['phase_gate_block_count'];
    }

    const changed = raw['changed_files'] ?? cli['changed_files'];
    if (Array.isArray(changed)) {
      evidence.changed_files = changed.map((c) =>
        typeof c === 'string' ? c : String((c as { path?: string }).path ?? c),
      );
    }

    const task = raw['task'] ?? cli['task'];
    if (typeof task === 'string') evidence.task = task;

    const cv = raw['completion_verification'] as
      | { verification?: { command?: string; exit_code?: number } | null }
      | undefined;
    if (cv?.verification?.command) {
      evidence.verification = [
        {
          command: cv.verification.command,
          status: cv.verification.exit_code === 0 ? 'passed' : 'failed',
          exit_code: cv.verification.exit_code ?? null,
        },
      ];
    }
    break;
  }

  // policy-events / why-stopped companion
  const policyPath = join(runDir, 'policy-events.jsonl');
  if (existsSync(policyPath)) {
    evidence.notes = evidence.notes ?? [];
    evidence.notes.push('policy-events.jsonl present');
  }

  return evidence;
}

function safeList(dir: string): string[] {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

/**
 * Merge CI review + optional run evidence into one PR body payload.
 */
export function mergeShipEvidenceSources(input: {
  runEvidence?: ImplementorShipEvidence;
  changedFiles?: string[];
  verification?: ImplementorShipEvidence['verification'];
  task?: string;
  prSummary?: string[];
  prTestPlan?: string[];
}): ImplementorShipEvidence {
  const base = { ...(input.runEvidence ?? {}) };
  if (input.changedFiles?.length) {
    base.changed_files = [...new Set([...(base.changed_files ?? []), ...input.changedFiles])];
  }
  if (input.verification?.length) {
    base.verification = input.verification;
  }
  if (input.task) base.task = input.task;
  if (input.prSummary?.length) {
    base.notes = [...(base.notes ?? []), ...input.prSummary.map((s) => `draft: ${s}`)];
  }
  if (input.prTestPlan?.length) {
    base.notes = [...(base.notes ?? []), ...input.prTestPlan.map((t) => `test plan: ${t}`)];
  }
  return base;
}
