[CmdletBinding()]
param(
  [Parameter(Mandatory = $true)][string]$BaseSha,
  [Parameter(Mandatory = $true)][string]$HeadSha,
  [string]$RepoRoot = (Join-Path $PSScriptRoot '..')
)

# TrustRootRecoveryV1 path-allowlist machine check (campaign Phase 21).
#
# A recovery candidate may only touch the authority registries, required
# recovery metadata, and explicitly justified verifier compatibility changes.
# No product changes, provider work, unrelated docs, refactors, or CI cleanup
# may ride a recovery merge. Run by the recovery operator before staging the
# recovery PR and re-run by review tooling immediately before the merge; a
# non-zero exit means the candidate is not a legal recovery candidate.
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

if ($BaseSha -notmatch '^[0-9a-fA-F]{40}$' -or $HeadSha -notmatch '^[0-9a-fA-F]{40}$') { throw 'Recovery scope requires exact commit SHAs.' }
$root = (Resolve-Path -LiteralPath $RepoRoot -ErrorAction Stop).Path
$git = (Get-Command git -ErrorAction Stop).Source

# Exact recovery allowlist. Registry files plus narrowly named recovery
# metadata; anything else (including new paths) must go through an ordinary
# PR, never a recovery merge.
$allowedExact = @(
  'config/independent-review-keys.json',
  'config/trusted-supervisor-keys.json',
  'docs/architecture/TRUST_ROOT_RECOVERY.md'
)
# Prefix-scoped recovery metadata (incident records generated by the recovery
# workflow itself).
$allowedPrefixes = @(
  '.babel/recovery/'
)

$paths = @(& $git -C $root diff --name-only ("{0}...{1}" -f $BaseSha, $HeadSha) | ForEach-Object { [string]$_ } | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
if ($LASTEXITCODE -ne 0) { throw 'Cannot inspect recovery candidate diff.' }
if ($paths.Count -eq 0) { throw 'Recovery candidate diff is empty.' }

$unexpected = @()
foreach ($path in $paths) {
  $allowed = $false
  if ($allowedExact -contains $path) { $allowed = $true }
  foreach ($prefix in $allowedPrefixes) {
    if ($path.StartsWith($prefix, [StringComparison]::Ordinal)) { $allowed = $true; break }
  }
  if (-not $allowed) { $unexpected += $path }
}

if ($unexpected.Count -gt 0) {
  Write-Error ("RECOVERY_SCOPE_VIOLATION unexpected paths: {0}" -f ($unexpected -join ', '))
  exit 1
}
Write-Output 'RECOVERY_SCOPE_OK'
