[CmdletBinding()]
param(
    [string]$Root = ""
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ([string]::IsNullOrWhiteSpace($Root)) {
    $scriptDir = if ($PSScriptRoot) { $PSScriptRoot } else { Split-Path -Path $PSCommandPath -Parent }
    $Root = (Resolve-Path (Join-Path $scriptDir "..")).Path
}

$syncPath = Join-Path $Root "tools\sync-model-manifests.ps1"
$resolverPath = Join-Path $Root "tools\resolve-control-plane.ps1"
$configPath = Join-Path $Root "tools\model-manifest-sources.json"
$manifestFiles = @("AGENTS.md", "CLAUDE.md", "GEMINI.md")

foreach ($requiredPath in @($syncPath, $resolverPath, $configPath)) {
    if (-not (Test-Path $requiredPath)) {
        throw "Required file not found: $requiredPath"
    }
}

function Get-ManifestHashes {
    param(
        [Parameter(Mandatory = $true)]
        [string]$BaseRoot,

        [Parameter(Mandatory = $true)]
        [string[]]$FileNames
    )

    $hashes = @{}
    foreach ($name in $FileNames) {
        $path = Join-Path $BaseRoot $name
        if (-not (Test-Path $path)) {
            throw "Manifest file missing: $path"
        }

        $hashes[$name] = (Get-FileHash -Path $path -Algorithm SHA256).Hash.ToUpperInvariant()
    }

    return $hashes
}

function Assert-Equal {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Label,

        [AllowNull()]
        [object]$Expected,

        [AllowNull()]
        [object]$Actual
    )

    if ([string]$Expected -ne [string]$Actual) {
        throw "$Label mismatch. Expected '$Expected' but got '$Actual'."
    }
}

function Assert-Contains {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Label,

        [Parameter(Mandatory = $true)]
        [string]$Text,

        [Parameter(Mandatory = $true)]
        [string]$Fragment
    )

    if (-not $Text.Contains($Fragment)) {
        throw "$Label missing expected fragment: $Fragment"
    }
}

powershell -ExecutionPolicy Bypass -File $syncPath -Root $Root | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "sync-model-manifests.ps1 exited with code $LASTEXITCODE on first run."
}

$hashesAfterFirstRun = Get-ManifestHashes -BaseRoot $Root -FileNames $manifestFiles

powershell -ExecutionPolicy Bypass -File $syncPath -Root $Root | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "sync-model-manifests.ps1 exited with code $LASTEXITCODE on second run."
}

$hashesAfterSecondRun = Get-ManifestHashes -BaseRoot $Root -FileNames $manifestFiles

foreach ($manifestFile in $manifestFiles) {
    Assert-Equal `
        -Label "$manifestFile idempotence hash" `
        -Expected $hashesAfterFirstRun[$manifestFile] `
        -Actual $hashesAfterSecondRun[$manifestFile]

    $manifestPath = Join-Path $Root $manifestFile
    $manifestText = Get-Content -Path $manifestPath -Raw

    Assert-Contains -Label "$manifestFile header" -Text $manifestText -Fragment "Generated by: tools/sync-model-manifests.ps1"
    Assert-Contains -Label "$manifestFile resolver" -Text $manifestText -Fragment "Resolver: tools/resolve-control-plane.ps1"
    Assert-Contains -Label "$manifestFile source config" -Text $manifestText -Fragment "Manifest Sources Config: tools/model-manifest-sources.json"
    Assert-Contains -Label "$manifestFile canonical section" -Text $manifestText -Fragment "## Canonical Source Inputs"
    Assert-Contains -Label "$manifestFile model hash" -Text $manifestText -Fragment "Model Rules SHA256:"

    if ($manifestText.Contains("Generated UTC:")) {
        throw "$manifestFile should not contain a non-deterministic Generated UTC field."
    }
}

powershell -ExecutionPolicy Bypass -File $syncPath -Root $Root -Check | Out-Null
if ($LASTEXITCODE -ne 0) {
    throw "sync-model-manifests.ps1 -Check exited with code $LASTEXITCODE."
}

Write-Host "sync-model-manifests regression tests passed." -ForegroundColor Cyan
